### ISSUE TITLE
点了编辑再点新建,数据还在

### ISSUE THREAD

**Issue by qqjay2017** [topfullstack/node-vue-moba#1]
会这样吗

**Comment by yuzhewo** [comment]
会的

**Comment by qqjay2017** [comment]
这算bug吗,咋整,(很喜欢看您的视频,很多在第二遍看了,)

**Comment by wxs77577** [comment]
后面修复了

**Comment by puck1006** [comment]
为什么我服务器也开了  为啥状态码还是500！！！！！

**Comment by qqjay2017** [comment]
> 为什么我服务器也开了 为啥状态码还是500！！！！！

500是后端问题,

**Comment by mobeiqingkong** [comment]
？？？谁啊




------------------ 原始邮件 ------------------
发件人: "huangsir"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 上午9:17
收件人: "wxs77577/node-vue-moba"<node-vue-moba@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [wxs77577/node-vue-moba] 点了编辑再点新建,数据还在 (#1)



 
为什么我服务器也开了 为啥状态码还是500！！！！！
  
500是后端问题,

**Comment by puck1006** [comment]
我也清楚是后端问题就是不晓得怎么解决

**Comment by mobeiqingkong** [comment]
你是谁啊。。。


 
---原始邮件---
发件人: "puck1006"<notifications@github.com&gt;
发送时间: 2019年8月29日 11:09:33
收件人: "wxs77577/node-vue-moba"<node-vue-moba@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Mobius"<1849923303@qq.com&gt;;
主题: Re: [wxs77577/node-vue-moba] 点了编辑再点新建,数据还在 (#1)



我也清楚是后端问题就是不晓得怎么解决

**Comment by puck1006** [comment]
什么我是谁，我在github上留言了啊------------------ 原始邮件 ------------------
发件人: "Mobius"<notifications@github.com>
发送时间: 2019年8月29日(星期四) 中午11:10
收件人: "wxs77577/node-vue-moba"<node-vue-moba@noreply.github.com>;
抄送: "puck1006"<435590668@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wxs77577/node-vue-moba] 点了编辑再点新建,数据还在 (#1)


你是谁啊。。。 
 
 
   
 ---原始邮&#x4EF6;--- 
 发&#x4EF6;人: "puck1006"<notifications@github.com&gt; 
 发送时间: 2019年8月29日 11:09:33 
 收&#x4EF6;人: "wxs77577/node-vue-moba"<node-vue-moba@noreply.github.com&gt;; 
 抄送: "Comment"<comment@noreply.github.com&gt;;"Mobius"<1849923303@qq.com&gt;; 
 主题: Re: [wxs77577/node-vue-moba] 点了编辑再点新建,数据还在 (#1) 
 
 
 
 我也清&#x695A;是后端问题就是不&#x6653;得怎么解决 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by jessy-x** [comment]
数据库文件呢

**Comment by chengazhen** [comment]
你这是前端组件复用,数据还在,你vue学会了吗,就来学后端
